positions:
  OUTLEFT: #Outside of the screen, left side
    x: -133
    y: 600 #The y should be at the bottom of the screen
  LEFT: 
    x: 133
    y: 600
  CENTER: 
    x: 400
    y: 600
  DEFAULT: 
    x: 400
    y: 600
  RIGHT: 
    x: 666
    y: 600
  OUTRIGHT: #Outside of the screen, right side
    x: 933
    y: 600

transitions:
  defaults: # Default transition when showing/hiding
    characters: FADE
    backgrounds: FADE
    cgs: FADE
    music: FADE
  say: CUT #How to change character expression in say action
  # Transition to use when showing/hiding choices
  visualChoices: FADE
  textChoices: CUT
  menus: FADE

# Fade transition time, in miliseconds
fadetime : 750
# Time in each action that waits (e.g. text and say) when skipping
skiptime: 50
# Time in each action that waits (e.g. text and say) when auto playing
autotime: 150
# Default waiting time for timeouts if not specified
timeout: 5000
# If logChoices is true, previously chosen choices will be shown in a different color
logChoices: true
# If logText is true, all executed say and text actions will be kept in a log that can be checked
logText: true


